
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'feature/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run TypeScript checks
        run: yarn run type-check || exit 1

      - name: Run lint
        run: yarn run lint || exit 1

      - name: Run tests
        run: yarn test || exit 1

      - name: Build project
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY }}
          JWT_SECRET: ${{secrets.JWT_SECRET }}
          SMTP_PORT: ${{secrets.SMTP_PORT }}
          SMTP_PASS: ${{secrets.SMTP_PASS }}
          SMTP_USER: ${{secrets.SMTP_USER }}
          SMTP_HOST: ${{secrets.SMTP_HOST }}
          SUPABASE_URL: ${{secrets.SUPABASE_URL }}
          NEXT_PUBLIC_APP_URL: ${{secrets.NEXT_PUBLIC_APP_URL }}
          STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY }}
        run: yarn run build || exit 1
        

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v20

        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: ${{ github.ref == 'refs/heads/main' }}


      - name: Save preview URL
        run: 'echo "Preview URL: ${{ steps.vercel.outputs.preview-url }}" > preview.txt'


      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: preview.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}